In [1]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
import os

print(os.getcwd())

c:\Users\rocky\Downloads\retail-demand-forecasting\notebooks

In [3]:
from src.data import load_data

print(load_data.__file__)

c:\Users\rocky\Downloads\retail-demand-forecasting\src\data\load_data.py

In [4]:
from src.data.load_data import load_data

train, test = load_data()

train.head()

Loading from: C:\Users\rocky\Downloads\retail-demand-forecasting\data\raw

        date  store  item  sales
0 2013-01-01      1     1     13
1 2013-01-02      1     1     11
2 2013-01-03      1     1     14
3 2013-01-04      1     1     13
4 2013-01-05      1     1     10

In [5]:
from src.data.load_data import load_data

train, test = load_data()

Loading from: C:\Users\rocky\Downloads\retail-demand-forecasting\data\raw

In [8]:
from src.data.load_data import load_data
from src.features.build_features import build_features

train, test = load_data()

train = build_features(train)

train.head()

Loading from: C:\Users\rocky\Downloads\retail-demand-forecasting\data\raw

,date,store,item,sales,year,month,day,day_of_week,day_of_year,week_of_year,quarter,is_weekend,lag_1,lag_7,lag_30,rolling_mean_7,rolling_mean_30,rolling_std_7
0,2013-01-31,1,1,13,2013,1,31,3,31,5,1,0,9.0,8.0,13.0,10.285714,10.500000,2.751623
1,2013-02-01,1,1,11,2013,2,1,4,32,5,1,0,13.0,14.0,11.0,11.000000,10.500000,2.708013
2,2013-02-02,1,1,21,2013,2,2,5,33,5,1,1,11.0,12.0,14.0,10.571429,10.500000,2.370453
3,2013-02-03,1,1,15,2013,2,3,6,34,5,1,1,21.0,12.0,13.0,11.857143,10.733333,4.634241
4,2013-02-04,1,1,14,2013,2,4,0,35,6,1,0,15.0,11.0,10.0,12.285714,10.800000,4.785892

In [11]:
train_df = train[train["date"] < "2017-01-01"].copy()
test_df = train[train["date"] >= "2017-01-01"].copy()

features = [
    "store",
    "item",
    "year",
    "month",
    "day",
    "day_of_week",
    "day_of_year",
    "week_of_year",
    "quarter",
    "is_weekend",
    "lag_1",
    "lag_7",
    "lag_30",
    "rolling_mean_7",
    "rolling_mean_30",
    "rolling_std_7"
]

X_test = test_df[features]

In [12]:
from src.models.predict import predict

sample = X_test.iloc[:5]

predictions = predict(sample)

print(predictions)

[19.073692 13.111953 15.390703 14.697807 15.813406]